select top 10 * from customer order by customer_id asc
--Q1. What is the total revenue generated by male vs. female customers? (tổng doanh thu của khách hàng nam và nữ)
select gender ,sum(purchase_amount) as total_revenue from customer group by gender
--Q2. Which customers used a discount but still spent more than the average purchase amount? (khách hàng nào dùng mã giảm giá nhưng vẫn chi nhiều hơn chi tiêu trung bình)
select customer_id, purchase_amount from customer 
where discount_applied = 'Yes' and purchase_amount > (select AVG(purchase_amount) from customer)
-- Q3. Which are the top 5 products with the highest average review rating? (top 5 sản phẩm có rating trung bình cao nhất)
select top 5 item_purchased, avg(review_rating) as average_review_rating from customer 
group by item_purchased order by average_review_rating desc
--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. (so sánh chi tiêu đối của khách hàng sử dụng ship tiêu chuẩn và ship express) 
select shipping_type, AVG(purchase_amount) as average_purchase_amount from customer 
where shipping_type IN ('Express', 'Standard') group by shipping_type
--Q5. Do subscribed customers spend more? Compare average spend and total revenue (khách hàng đã đăng kí có chi tiêu nhiều hơn khách không đăng kí không?)
select subscription_status, sum(purchase_amount) as total_revenue, AVG(purchase_amount) as average_spend from customer
group by subscription_status
--Q6. Which 5 products have the highest percentage of purchases with discounts applied? (top 5 sản phẩm có tỉ lệ mua cao nhất khi dùng mã giảm giá)
SELECT TOP 5 item_purchased, AVG(CASE WHEN discount_applied = 'Yes' THEN 1.0 ELSE 0.0 END) * 100 AS percentage_of_purchases
FROM customer GROUP BY item_purchased ORDER BY percentage_of_purchases DESC
--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
--(phân loại khách hàng thành các nhóm KH Mới, KH có khả năng trở lại và KH trung thành dựa theo dự số lần mua trước đó và đếm số lượng của mỗi loại KH)
with customer_type as
(select customer_id, previous_purchases, 
	case 
	when previous_purchases = 1 then 'New Customer'
	when previous_purchases between 2 and 10 then 'Returning Customer'
	else 'Loyal Customer'
	end as customer_segment
from customer)

select customer_segment, COUNT(*) as number_of_customers from customer_type group by customer_segment order by number_of_customers desc
--Q8. What are the top 3 most purchased products within each category? (top 3 sản phẩm được mua nhiều nhất của mỗi loại)
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT category, item_rank, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe? (các khách hàng đã mua từ 5 lần trở lên có khả năng sẽ đăng kí không?)
select subscription_status, COUNT(previous_purchases) as repeat_buyers from customer 
where previous_purchases > 5 group by subscription_status order by repeat_buyers desc
--Q10. What is the revenue contribution of each age group? (doanh thu từ mỗi nhóm tuổi)
select age_group, SUM(purchase_amount) as revenue_contribution from customer 
group by age_group order by revenue_contribution desc